language: python
python:
  - "3.5"
install:
  - pip install coveralls
  - pip install colored --upgrade
script:
  - make
  - coverage erase
  - coverage run test.py test
after_success:
  - coverage combine
  - coveralls

